### ISSUE TITLE
Add contents about team on md file 

### ISSUE THREAD

**Issue by hann3** [urther/Zerobase-team-04#4]
- [x] 우리 조 소개

**Comment by mei-zy** [comment]
저희 팀 이름은.. 밥먹고4는4사람들 어떠신가요 ,, 
마음에 드신다면 팀 이름도 올려주세요 (임의로 정해주셔도 됩니다 👍🏻  )

**Comment by hann3** [comment]
1. 밥먹고4는4사람들
2. 먹하
좋은 아이디어. 이건 함께 상의해야 할 듯 합니다 ^^
